#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -l pmem=32gb
#PBS -A jlt22_b_g_sc_default #jlt22_b_g_sc_default or open
#PBS -j oe

#Go to folder
cd ~/work/ExtractPop

#Activate conda env
conda activate vcft

#Concatenate chromosomes
bcftools concat --file-list merge_list.txt --output-type z --output ~/scratch/EUR_1K.vcf.gz

#To plink bfiles
plink --vcf ~/scratch/EUR_1K.vcf.gz --make-bed --out ~/scratch/EUR_1K

#Write SNPlist with mafs
plink --bfile ~/scratch/EUR_1K --maf 0.01 --write-snplist --out ~/scratch/EUR_1K_Snps
#Remove those with low mafs
plink --bfile ~/scratch/EUR_1K --extract ~/scratch/EUR_1K_Snps.snplist --make-bed --out ~/scratch/EUR_1K_maf
#Write duplicates
cat ~/scratch/EUR_1K_Snps.snplist | sort | uniq -d > ~/scratch/EUR_1K_duplicated_snps.snplist
#Write a no_dup file
plink --bfile ~/scratch/EUR_1K_maf --exclude ~/scratch/EUR_1K_duplicated_snps.snplist --make-bed --out ~/scratch/EUR_1K_nodup
